# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

# Speed up build with travis caches
cache:
  directories:
    - $HOME/.gradle/wrapper/

language: java

#TODO why do we need below?
before_install:
  - export TRAVIS_COMMIT_MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - echo "$TRAVIS_COMMIT_MESSAGE"

jdk:
  - oraclejdk8

#TODO why do we need below?
env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-XX:+UseCompressedOops -Djava.awt.headless=true"

#don't build tags
branches:
  except:
  - /^v\d/

#Below skips the installation step completely (https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step)
install:
 - true

script:
  - ./gradlew build -s

after_success:
  - ./gradlew assertReleaseNeeded && ./gradlew ciReleasePrepare && ./gradlew performRelease -Pshipkit.dryRun=false